### ISSUE TITLE
Make dao.utils.query_list return empty list on error

### ISSUE THREAD

**Issue by RodionGork** [CodeAbbey/abbey2#14]
Current idea of handling errors is preferably not to throw exceptions uncaught. Perhaps this will be refined later. But for now let's make `dao.utils.query_list` return empty list on error (e.g. table was not found or connection lost, or something like this). This may require some testing.

**Comment by Rusty-Beard** [comment]
We can close this. Next time will use "fix" in the description

**Comment by RodionGork** [comment]
Ah, right, thanks! :)
