### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by Quandray** [CodeAbbey/abbey2#17]
Sorry, I don't have any of the skills required to help with this, so all I can do is "testing".
I've been away for the weekend. Before I went away, I was able to login using my codeabbey username and password. Now it says "Wrong username or password!"

**Comment by RodionGork** [comment]
Graeme, Hi!

Thanks for your suggestion! This would be cool :)

(as of skills - some of the issues require almost none of them and could be fixed even using web-interface of github - some are about spelling or look-n-feel, i.e. html/css, like #6 or #15)

I think the matter with issue you describe is that before today the site really wasn't checking user at all. It was allowing in with any combination of username/password. Today I at last was able to connect this behavior to database, so now one needs first "register" user (providing aditionally anything in email field). 

Though you are right, it would be good to have "interoperability" with existing CodeAbbey accounts in future.
