### ISSUE TITLE
Test new problem 'prg-4'

### ISSUE THREAD

**Issue by RodionGork** [CodeAbbey/abbey2#23]
Here is a new problem (not copied from old site):

https://rodiongork.pythonanywhere.com/tasks/view/prg-4

Not quite sure I've solved it correctly... And whether everything is ok with checker etc...

I hope, @Quandray you may be curious to test it :)

**Comment by Quandray** [comment]
Lovely problem.

If I press Submit without entering an answer, it tells me the correct answer. I can then go back and enter the correct answer.

It gave me 6627557 285 and confirmed that my calculated answer was correct.

**Comment by RodionGork** [comment]
> If I press Submit without entering an answer, it tells me the correct answer. I can then go back and enter the correct answer.

oh... what a "feature" :)

Thanks a lot for finding this - I'll go and see how this should be fixed!
