### ISSUE TITLE
Cheat with double submission

### ISSUE THREAD

**Issue by RodionGork** [CodeAbbey/abbey2#26]
Reported by @Quandray in #23 , this can be reproduced in several ways, e.g.:

- open the same problem in two tabs
- submit anything from first tab and get wrong answer
- copy correct "expected answer" to second tab and submit
- now the task is probably accepted, though it shouldn't

The matter is that expected answer is stored in session and on old site it was living on server. New site uses client-side session, so that cookie even if we clean it manually after submission, could still be duplicated... It looks like the only true way is to store expected answer on server-side and clean on checking...

**Comment by RodionGork** [comment]
I've added small dictionary to serve as server session and store these data there. Hopefully this will help.

**Comment by Quandray** [comment]
The fix seems to work. I saw "Something unexpected" when I tried to repeat it.

**Comment by RodionGork** [comment]
@Quandray yes, thanks for confirmation! I haven't yet decided what message to show (so it may be slightly bewildering) - but it could be improved later.

Hopefully after adding "try again" link (#24) people won't use "back" button often...

**Comment by Quandray** [comment]
Anyone who gets "wrong answer" is likely to press "back"

**Comment by RodionGork** [comment]
Hm-m-m, thanks. Then probably I need to find out how to force proper page reloading on pressing "back"... I'll check how it works on existing site, perhaps it is something about disabling page cache...

**Comment by RodionGork** [comment]
Well, I have learnt something new today :) some browsers do reload the page on the "back" button, and some (in my case Firefox) don't.

I've made pages sending the same "no-cache" headers as existing site does, so back button should work properly now. I.e. on pressing back after submission one must see new input values, not the same as previously...

**Comment by Quandray** [comment]
That looks fine with Firefox, Opera, Chome & IE

**Comment by RodionGork** [comment]
Thanks a lot for helping to find and check this! Let's close it for now...
