### ISSUE TITLE
Small difficulty with Problem Volumes page

### ISSUE THREAD

**Issue by Quandray** [CodeAbbey/abbey2#36]
a) the text says "These small exercises doesn't suppose plain and straightforward solution,".
I think it would be better to say "These small exercises don't support plain and straightforward solutions,"

b) The page displays ok for me using Chrome, but in Firefox and Opera it looks like
![image](https://user-images.githubusercontent.com/12142025/48312773-a712de00-e5ab-11e8-8f6f-64b83bda525d.png)

**Comment by RodionGork** [comment]
I failed to find a way to make these extra lines semi-transparent or something like this - so let's have these descriptions limited to some sane length. Full description (as seen on the volume list itself) may be longer - any additional information is just separated with two line breaks (and not shown in these pads).

Phrase also was corrected... I think more than once :) Please feel free to point any mistakes and awkward expressions which may need to be improved!
